export const SHIPPING_ADDRESS_LIST_REQUEST = 'SHIPPING_ADDRESS_LIST_REQUEST';
export const SHIPPING_ADDRESS_LIST_SUCCESS = 'SHIPPING_ADDRESS_LIST_SUCCESS';
export const SHIPPING_ADDRESS_LIST_FAILURE = 'SHIPPING_ADDRESS_LIST_FAILURE';

export const SHIPPING_ADDRESS_BY_ID_LIST_REQUEST = 'SHIPPING_ADDRESS_BY_ID_LIST_REQUEST';
export const SHIPPING_ADDRESS_BY_ID_LIST_SUCCESS = 'SHIPPING_ADDRESS_BY_ID_LIST_SUCCESS';
export const SHIPPING_ADDRESS_BY_ID_LIST_FAILURE = 'SHIPPING_ADDRESS_BY_ID_LIST_FAILURE';