export const CHEF_PLATES_REQUEST = 'CHEF_PLATES_REQUEST';
export const CHEF_PLATES_SUCCESS = 'CHEF_PLATES_SUCCESS';
export const CHEF_PLATES_FAILURE = 'CHEF_PLATES_FAILURE';

export const CHEF_ADD_PLATES_REQUEST = 'CHEF_ADD_PLATES_REQUEST';

export const CHEF_ADD_PLATES_SUCCESS = 'CHEF_ADD_PLATE_SUCCESS';

export const CHEF_ADD_PLATES_FAILURE = 'CHEF_ADD_PLATES_FAILURE';

export const CHEF_ADD_PLATES_IMAGES_REQUEST = 'CHEF_ADD_PLATES_IMAGES_REQUEST';

export const CHEF_ADD_PLATES_IMAGES_SUCCESS = 'CHEF_ADD_PLATES_IMAGES_SUCCESS';

export const CHEF_ADD_PLATES_IMAGES_FAILURE = 'CHEF_ADD_PLATES_IMAGES_FAILURE';
