//food

export const SET_IS_FETCHING_FOOD = 'SET_IS_FETCHING_FOOD';

export const SET_ERROR_FETCHING_FOOD = 'SET_ERROR_FETCHING_FOOD';

export const ADD_FOOD_TO_COLLECTION = 'ADD_FOOD_TO_COLLECTION';

//category

export const SET_IS_FETCHING_FOOD_CATEGORY = 'SET_IS_FETCHING_FOOD_CATEGORY';

export const SET_ERROR_FETCHING_FOOD_CATEGORY = 'SET_ERROR_FETCHING_FOOD_CATEGORY';

export const ADD_FOOD_CATEGORY_TO_COLLECTION = 'ADD_FOOD_CATEGORY_TO_COLLECTION';

//popular_and_new

export const SET_IS_FETCHING_POPULAR_AND_NEW = 'SET_IS_FETCHING_POPULAR_AND_NEW';

export const SET_ERROR_FETCHING_POPULAR_AND_NEW = 'SET_ERROR_FETCHING_POPULAR_AND_NEW';

export const ADD_POPULAR_FOOD_TO_COLLECTION = 'ADD_POPULAR_FOOD_TO_COLLECTION';

export const ADD_NEW_FOOD_TO_COLLECTION = 'ADD_NEW_FOOD_TO_COLLECTION';
