export const CART_ADD_PLATE_REQUEST = 'CART_ADD_PLATE_REQUEST';
export const CART_ADD_PLATE_SUCCESS = 'CART_ADD_PLATE_SUCCESS';
export const CART_ADD_PLATE_FAILURE = 'CART_ADD_PLATE_FAILURE';

export const CART_ADD_MULTI_PLATE_REQUEST = 'CART_ADD_MULTI_PLATE_REQUEST';
export const CART_ADD_MULTI_PLATE_SUCCESS = 'CART_ADD_MULTI_PLATE_SUCCESS';
export const CART_ADD_MULTI_PLATE_FAILURE = 'CART_ADD_MULTI_PLATE_FAILURE';

export const CART_INCREASE_ITEM_REQUEST = 'CART_INCREASE_ITEM_REQUEST';
export const CART_INCREASE_ITEM_SUCCESS = 'CART_INCREASE_ITEM_SUCCESS';
export const CART_INCREASE_ITEM_FAILURE = 'CART_INCREASE_ITEM_FAILURE';

export const CART_DECREASE_ITEM_REQUEST = 'CART_DECREASE_ITEM_REQUEST';
export const CART_DECREASE_ITEM_SUCCESS = 'CART_DECREASE_ITEM_SUCCESS';
export const CART_DECREASE_ITEM_FAILURE = 'CART_DECREASE_ITEM_FAILURE';

export const CART_REMOVE_PLATE_REQUEST = 'CART_REMOVE_PLATE_REQUEST';
export const CART_REMOVE_PLATE_SUCCESS = 'CART_REMOVE_PLATE_SUCCESS';
export const CART_REMOVE_PLATE_FAILURE = 'CART_REMOVE_PLATE_FAILURE';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_INCREASE_ITEM = 'CART_INCREASE_ITEM';
export const CART_DECREASE_ITEM = 'CART_DECREASE_ITEM';

export const CART_SET_ITEM_COUNT = 'CART_SET_ITEM_COUNT';
export const CART_SET_ITEM_COUNT_WITH_SESSION_FLAG = 'CART_SET_ITEM_COUNT_WITH_SESSION_FLAG';
export const CART_SET_ITEM_COUNT_WITHOUT_SESSION_FLAG = 'CART_SET_ITEM_COUNT_WITHOUT_SESSION_FLAG';